USE DATABASE WEBACCESSIBLE;
USE SCHEMA APP;

-- The table already exists in the configured account. CREATE plus additive ALTERs
-- make this migration safe for both a fresh environment and the live baseline.
CREATE TABLE IF NOT EXISTS SESSION_STEPS (
    session_id STRING,
    user_id STRING,
    step_no INTEGER,
    task_name STRING,
    skill_id STRING,
    url_domain STRING,
    action STRING,
    model_used STRING,
    input_tokens INTEGER,
    output_tokens INTEGER,
    credits NUMBER(18, 9),
    replayed_from_memory BOOLEAN,
    latency_ms INTEGER,
    outcome STRING,
    ts TIMESTAMP_NTZ
)
COMMENT = 'One row per observed or guided WebAccessible session step.';

ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS event_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS schema_version INTEGER;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS run_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS task_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS step_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS guidance_mode STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS sync_attempt INTEGER;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS source_environment STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS browserbase_session_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS page_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS page_instance_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS model_call_id STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS selector_tier STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS selector_result STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS verification_predicate STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS verification_result STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS trusted_user_action BOOLEAN;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS terminal_provenance STRING;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS synchronized_at TIMESTAMP_NTZ;
ALTER TABLE SESSION_STEPS ADD COLUMN IF NOT EXISTS ingested_at TIMESTAMP_NTZ;

ALTER TABLE SESSION_STEPS SET COMMENT =
    'WebAccessible product-owned step telemetry. Values originate in the backend; fixture rows never qualify for live views.';
